language: java
before_install:
- sudo apt-get -qq update
- sudo apt-get install ant-optional
- sudo apt-get install junit
addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ant
            - ant-optional
jdk:
  - oraclejdk9
script: ant "uiTest (1)" "scoreTest (1)"
dist: trusty
